services:
  prisma-init:
    image: ghcr.io/holashchand/prisma-init:1.0.0
    networks:
      - sunbird-rc-core_default
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public

networks:
  sunbird-rc-core_default:
    external: true